-- MySQL Script generated by MySQL Workbench
-- Wed Sep 19 13:15:58 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema database
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `database` ;

-- -----------------------------------------------------
-- Schema database
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `database` DEFAULT CHARACTER SET utf8 ;
USE `database` ;

-- -----------------------------------------------------
-- Table `database`.`Bet`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `database`.`Bet` ;

CREATE TABLE IF NOT EXISTS `database`.`Bet` (
  `idBet` INT NOT NULL,
  `idCompetitor` INT NULL,
  `idRound` INT NULL,
  `idProblem` INT NULL,
  `betTime` DATE NULL,
  PRIMARY KEY (`idBet`),
  INDEX `idCompetitor_idx` (`idCompetitor` ASC) VISIBLE,
  INDEX `idRound_idx` (`idRound` ASC) VISIBLE,
  INDEX `idProblem_idx` (`idProblem` ASC) VISIBLE,
  CONSTRAINT `idCompetitor`
    FOREIGN KEY (`idCompetitor`)
    REFERENCES `database`.`Competitors` (`idCompetitors`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `idRound`
    FOREIGN KEY (`idRound`)
    REFERENCES `database`.`Round` (`idRound`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `idProblem`
    FOREIGN KEY (`idProblem`)
    REFERENCES `database`.`Problem` (`idProblem`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `database`.`Challenge`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `database`.`Challenge` ;

CREATE TABLE IF NOT EXISTS `database`.`Challenge` (
  `idChallenge` INT NOT NULL,
  `idUserChallenged` INT NOT NULL,
  `idChallengingUser` INT NOT NULL,
  `idProblem` INT NOT NULL,
  `challengeTime` DATE NOT NULL,
  `idRound` INT NOT NULL,
  PRIMARY KEY (`idChallenge`),
  INDEX `idUserChallenged_idx` (`idUserChallenged` ASC, `idChallengingUser` ASC) VISIBLE,
  INDEX `idProblem_idx` (`idProblem` ASC) VISIBLE,
  INDEX `idRound_idx` (`idRound` ASC) VISIBLE,
  CONSTRAINT `idUsers`
    FOREIGN KEY (`idUserChallenged` , `idChallengingUser`)
    REFERENCES `database`.`Competitors` (`idCompetitors` , `idCompetitors`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `idProblem`
    FOREIGN KEY (`idProblem`)
    REFERENCES `database`.`Problem` (`idProblem`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `idRound`
    FOREIGN KEY (`idRound`)
    REFERENCES `database`.`Round` (`idRound`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `database`.`Competition`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `database`.`Competition` ;

CREATE TABLE IF NOT EXISTS `database`.`Competition` (
  `idCompetition` INT NOT NULL,
  `nameCompetition` VARCHAR(45) NOT NULL,
  `passwordCompetition` VARCHAR(45) NULL,
  `timeStart` VARCHAR(45) NOT NULL,
  `timeEnd` VARCHAR(45) NOT NULL,
  `timeCreated` VARCHAR(45) NOT NULL,
  `listCompetitors` INT NOT NULL,
  `listJudges` INT NOT NULL,
  PRIMARY KEY (`idCompetition`),
  INDEX `idCompetitors_idx` (`listCompetitors` ASC) VISIBLE,
  INDEX `idJudge_idx` (`listJudges` ASC) VISIBLE,
  CONSTRAINT `idCompetitors`
    FOREIGN KEY (`listCompetitors`)
    REFERENCES `database`.`Competitors` (`idCompetitors`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `idJudge`
    FOREIGN KEY (`listJudges`)
    REFERENCES `database`.`Judge` (`idJudge`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `database`.`Competitors`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `database`.`Competitors` ;

CREATE TABLE IF NOT EXISTS `database`.`Competitors` (
  `idCompetitors` INT NOT NULL,
  `idPerson` INT NULL,
  PRIMARY KEY (`idCompetitors`),
  INDEX `idPerson_idx` (`idPerson` ASC) VISIBLE,
  CONSTRAINT `idPerson`
    FOREIGN KEY (`idPerson`)
    REFERENCES `database`.`Person` (`idPerson`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `database`.`Judge`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `database`.`Judge` ;

CREATE TABLE IF NOT EXISTS `database`.`Judge` (
  `idJudge` INT NOT NULL,
  `nameJudge` VARCHAR(45) NULL,
  `typeJudge` VARCHAR(45) NULL,
  PRIMARY KEY (`idJudge`))
ENGINE = InnoDB
COMMENT = '	';


-- -----------------------------------------------------
-- Table `database`.`Keyword`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `database`.`Keyword` ;

CREATE TABLE IF NOT EXISTS `database`.`Keyword` (
  `idKeyword` INT NOT NULL,
  `shortKeyword` VARCHAR(45) NULL,
  `descpKeyword` VARCHAR(45) NULL,
  PRIMARY KEY (`idKeyword`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `database`.`Person`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `database`.`Person` ;

CREATE TABLE IF NOT EXISTS `database`.`Person` (
  `idPerson` INT NOT NULL,
  `firstName` VARCHAR(45) NULL,
  `secondName` VARCHAR(45) NULL,
  `lastName` VARCHAR(45) NULL,
  `secondLastName` VARCHAR(45) NULL,
  `username` VARCHAR(45) NOT NULL,
  `password` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `country` VARCHAR(45) NULL,
  `dateCreatedCompetitor` DATETIME NOT NULL,
  PRIMARY KEY (`idPerson`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `database`.`Points`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `database`.`Points` ;

CREATE TABLE IF NOT EXISTS `database`.`Points` (
  `idCompetitor` INT NULL,
  `idCompetition` INT NULL,
  `points` VARCHAR(45) NULL,
  INDEX `idCompetitor_idx` (`idCompetitor` ASC) VISIBLE,
  INDEX `idCompetition_idx` (`idCompetition` ASC) VISIBLE,
  CONSTRAINT `idCompetitor`
    FOREIGN KEY (`idCompetitor`)
    REFERENCES `database`.`Competitors` (`idCompetitors`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `idCompetition`
    FOREIGN KEY (`idCompetition`)
    REFERENCES `database`.`Competition` (`idCompetition`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `database`.`Problem`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `database`.`Problem` ;

CREATE TABLE IF NOT EXISTS `database`.`Problem` (
  `idProblem` INT NOT NULL,
  `textProblem` VARCHAR(45) NULL,
  `listSolutions` INT NULL,
  `bet` INT NULL,
  `challenge` VARCHAR(45) NULL,
  `idSend` INT NULL,
  `idSubject` INT NULL,
  `idKeyword` INT NULL,
  `Problemcol` VARCHAR(45) NULL,
  PRIMARY KEY (`idProblem`),
  INDEX `idSubject_idx` (`idSubject` ASC) VISIBLE,
  INDEX `idKeyword_idx` (`idKeyword` ASC) VISIBLE,
  CONSTRAINT `idSubject`
    FOREIGN KEY (`idSubject`)
    REFERENCES `database`.`Subject` (`idSubject`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `idKeyword`
    FOREIGN KEY (`idKeyword`)
    REFERENCES `database`.`Keyword` (`idKeyword`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `database`.`Round`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `database`.`Round` ;

CREATE TABLE IF NOT EXISTS `database`.`Round` (
  `idRound` INT NOT NULL,
  `timeLimitAnswer` VARCHAR(45) NOT NULL,
  `timeLimitBet` VARCHAR(45) NOT NULL,
  `timeLimitChallenge` VARCHAR(45) NOT NULL,
  `minimumBet` VARCHAR(45) NOT NULL,
  `maximumBet` VARCHAR(45) NOT NULL,
  `idCompetition` INT NOT NULL,
  `listProblems` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idRound`),
  INDEX `idCompetition_idx` (`idCompetition` ASC) VISIBLE,
  INDEX `listProblems_idx` (`listProblems` ASC) VISIBLE,
  CONSTRAINT `idCompetition`
    FOREIGN KEY (`idCompetition`)
    REFERENCES `database`.`Competition` (`idCompetition`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `listProblems`
    FOREIGN KEY (`listProblems`)
    REFERENCES `database`.`Problem` (`idProblem`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `database`.`Solution`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `database`.`Solution` ;

CREATE TABLE IF NOT EXISTS `database`.`Solution` (
  `idSolution` INT NOT NULL,
  `typeSolution` VARCHAR(45) NOT NULL,
  `idProblem` INT NOT NULL,
  `listSolution` VARCHAR(45) NULL,
  PRIMARY KEY (`idSolution`),
  INDEX `fk_Solution_Problem1_idx` (`idProblem` ASC) VISIBLE,
  CONSTRAINT `fk_Solution_Problem1`
    FOREIGN KEY (`idProblem`)
    REFERENCES `database`.`Problem` (`idProblem`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `database`.`Subject`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `database`.`Subject` ;

CREATE TABLE IF NOT EXISTS `database`.`Subject` (
  `idSubject` INT NOT NULL,
  `shotSubject` VARCHAR(45) NOT NULL,
  `descpSubject` VARCHAR(45) NOT NULL,
  `idKeyword` INT NOT NULL,
  PRIMARY KEY (`idSubject`),
  INDEX `fk_Subject_Keyword1_idx` (`idKeyword` ASC) VISIBLE,
  CONSTRAINT `fk_Subject_Keyword1`
    FOREIGN KEY (`idKeyword`)
    REFERENCES `database`.`Keyword` (`idKeyword`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
